// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bolg/type/empty.proto

package bolg_developers.bolg.type;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.type.Empty)
    com.google.protobuf.MessageOrBuilder {
}
