// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bolg/hello/v1/hello.proto

package bolg_developers.bolg.hello.v1;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bolg.hello.v1.GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
